### ISSUE TITLE
Add support ethernet (usb-rj45)

### ISSUE THREAD

**Issue by vodkon** [capcom6/android-sms-gateway#68] opened 2024-05-16 10:31 UTC
The application does not seem to work after connecting the Internet to the phone via an Ethernet cable, it does not display the local IP address in the application, the application works properly with WiFi. 
Please add support for the ethernet port

**Comment by capcom6** [comment] 2024-05-16 10:53
Hello!

Can you provide some more information:

1. When you mention the app "does not seem to work," could you clarify whether the app crashes, or if the issue is that you are unable to connect to the local server using the device's IP address from the device's network settings?
2. Can you please confirm which version of the app you are currently using? As of [v1.12.3](https://github.com/capcom6/android-sms-gateway/releases/tag/v1.12.3), the app should be able to retrieve the local IP from any network interface, not just the `wlan`.
3. When connecting via Ethernet, do you ensure that the WiFi is turned off on your device?
4. With the Ethernet connection active, what IP address is displayed in the app? Is this IP address actually assigned to any of the device's network interfaces?

Thank you.

**Closed** 2024-05-24 07:06 UTC
Labels: enhancement

**Comment by capcom6** [comment] 2024-05-28 01:50
I have not received further information to assist with troubleshooting this issue. Due to the lack of response, I closed this issue. If you have additional details to provide, please feel free to reopen the issue or create a new one.

Thank you for your understanding.
