### ISSUE TITLE
RESULT_RIL_MODEM_ERR

### ISSUE THREAD

**Issue by kornblumenapotheke** [capcom6/android-sms-gateway#57] opened 2024-04-16 06:34 UTC
When trying to send a text, I get failed and RESULT_RIL_MODEM_ERR in the android app.

Android 12
Kernel 4.9.227
LG Velvet

App version: 1.12.1

**Comment by kornblumenapotheke** [comment] 2024-04-16 08:00
OK, Error found, the SIM was deactivated by provider :(

**Comment by capcom6** [comment] 2024-04-16 12:46
I'm glad to hear that you've identified the cause of the problem.

I'll go ahead and close this issue now, but should you encounter any further problems or have additional questions, please don't hesitate to open a new issue.

**Closed by capcom6** 2024-04-16 12:46 UTC
